# Generated by Django 3.1.5 on 2021-01-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_content',
            field=models.TextField(default='nothing about it'),
            preserve_default=False,
        ),
    ]
